install.packages('olsrr')
library(olsrr)
model<-lm(mpg~disp+hp+wt+qsec, data=mtcars)
k<-ols_step_all_possible(model)
plot(k)
k
model1<-lm(mpg~hp+wt, data=mtcars)
model2<-lm(mpg~hp+wt+qsec, data=mtcars)
summary(model1)
summary(model2)
